name: ci

on:
  push:

env:
  REGISTRY_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/nimbus-eth1:${{ github.head_ref || github.ref_name }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: linux
            cpu: amd64
          - os: linux
            cpu: arm64
        include:
          - target:
              cpu: amd64
            builder: ubuntu-latest
          - target:
              cpu: arm64
            builder: ubuntu-24.04-arm
    name: '${{ matrix.target.os }}/${{ matrix.target.cpu }}'
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.target.os }}/${{ matrix.target.cpu }}
          # Replace '/' with '-' to create a unique identifier for this platform
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.REGISTRY_IMAGE }}
            ${{ env.REGISTRY_IMAGE }}-${{ env.PLATFORM_PAIR }}
            ${{ env.REGISTRY_IMAGE }}-${{ env.PLATFORM_PAIR }}-${{ github.sha }}
